#include<bits/stdc++.h>
using namespace std;
typedef long long ll;
#define F first
#define S second
#define all(a)  a.begin(),a.end()
#define rall(a) a.rbegin(),a.rend()
#define pf push_front
#define pb push_back
#define MX INT_MAX
#define MN INT_MIN
#define inf 2e16
#define loop(i,n) for(int i = 0; i < (n); i++)
#define loop1(i,n) for(int i = 1; i <= (n); i++)
#define SZ(x) ((int)(x).size())
#define int ll
#define AhmedPlusPlus ios::sync_with_stdio(0); cin.tie(0); cout.tie(0);
/******************************************************************************************/
ll mod= 1e9+7;
void cin_v (vector <int> &v,int SIZE ){
    for (int i =0;i<SIZE;i++){
        int inp;cin >>inp;
        v.push_back(inp);
    }
}
//freopen("input.txt", "r", stdin);
//freopen("output.txt", "w", stdout);
// cout <<fixed<<setprecision(6)<<any number;
/* string s;
    getline(cin, s); */
//bitset<30>bits={20};
void cin_v_ll (vector <ll> &v,int SIZE ){
    for (int i =0;i<SIZE;i++){
        ll inp;cin >>inp;
        v.push_back(inp);
    }
}
void print_v (vector<ll>v){
    for (ll num : v){
        cout<<num<<" ";
    }
    cout <<"\n";
}
string YN[2] = { "NO\n","YES\n" };
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// START FROM HERE :------

void pewpew() {



}

signed main() {
/* ^^^ */    AhmedPlusPlus    /* ^^^ */

//    ->> practice makes perfect

    int x_x = 1;
    cin >> x_x;
    while (x_x--) {
        pewpew();
    }

}
